# Generated by Django 4.2.11 on 2024-03-07 12:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=255)),
                ('about', models.TextField()),
                ('experience', models.CharField(max_length=125)),
                ('location', models.CharField(max_length=125)),
                ('movies_worked', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
            ],
        ),
    ]
