# Generated by Django 4.2.11 on 2024-03-07 14:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_professionaluser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaluser',
            name='posts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='professionaluser',
            name='profile_img',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='professionaluser',
            name='user_type',
            field=models.CharField(default='', max_length=125),
        ),
    ]
