# Generated by Django 4.2.11 on 2024-03-10 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_moviesworked_added_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=125)),
                ('thumbnail', models.TextField(default='', max_length=512)),
                ('description', models.TextField(default='', max_length=512)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.professionaluser')),
            ],
        ),
    ]
