# Generated by Django 4.2.11 on 2024-03-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='post_type',
            field=models.TextField(default='', max_length=512),
        ),
    ]
