# Generated by Django 4.2.11 on 2024-03-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_service_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='post_type',
            new_name='service_type',
        ),
    ]
